apiVersion: v1beta3
items:
- apiVersion: v1beta3
  kind: DeploymentConfig
  metadata:
    name: gitserver
  spec:
    replicas: 1
    selector:
      run-container: gitserver
    template:
      metadata:
        labels:
          run-container: gitserver
      spec:
        containers:
        - env:
          - name: PUBLIC_URL
            value: http://gitserver.myproject.local:8080
          - name: GIT_HOME
            value: /var/lib/git
          - name: HOOK_PATH
            value: /var/lib/git-hooks
          - name: ALLOW_GIT_PUSH
            value: "yes"
          - name: ALLOW_GIT_HOOKS
            value: "yes"
          - name: ALLOW_LAZY_CREATE
            value: "yes"
          - name: AUTOLINK_CONFIG
            value: /var/lib/gitsecrets/admin.kubeconfig
          - name: AUTOLINK_NAMESPACE
          - name: AUTOLINK_HOOK
            value: null
          - name: REQUIRE_GIT_AUTH
          - name: OPENSHIFTCONFIG
            value: /var/lib/gitsecrets/admin.kubeconfig
          image: openshift/origin-gitserver
          name: gitserver
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /var/lib/gitsecrets/
            name: config
            readOnly: true
        volumes:
        - name: config
          secret:
            secretName: gitserver-config
    triggers:
    - type: ConfigChange
- apiVersion: v1beta3
  kind: Secret
  metadata:
    name: gitserver-config
  spec:
    data:
      admin.kubeconfig: null
- apiVersion: v1beta3
  kind: Service
  metadata:
    name: gitserver
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      run-container: gitserver
kind: List
metadata: {}
