apiVersion: v1
kind: Template
metadata:
  name: automation-broker-apb
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: automation-broker-apb
    namespace: "${NAMESPACE}"

- apiVersion: batch/v1
  kind: Job
  metadata:
    name: automation-broker-apb
    namespace: "${NAMESPACE}"
  spec:
    backoffLimit: 5
    activeDeadlineSeconds: 300
    template:
      spec:
        restartPolicy: OnFailure
        serviceAccount: automation-broker-apb
        containers:
        - image: docker.io/automationbroker/automation-broker-apb:latest
          name: automation-broker-apb
          args: [ "provision", "-e", "broker_name=${NAMESPACE}" ]


parameters:
- description: Namespace of the project that is being deploy
  displayname: broker client cert key
  name: NAMESPACE
  value: "openshift-automation-service-broker"
