apiVersion: v1
kind: Template
metadata:
  name: automation-broker-apb-rbac
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: automation-broker-apb
  roleRef:
    name: cluster-admin
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - kind: ServiceAccount
    name: automation-broker-apb
    namespace: "${NAMESPACE}"

parameters:
- description: Namespace of the project that is being deploy
  displayname: broker client cert key
  name: NAMESPACE
  value: "openshift-automation-service-broker"
