apiVersion: v1
kind: Template
metadata:
  name: automation-broker-apb
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: automation-broker-apb
    namespace: "${NAMESPACE}"

- apiVersion: batch/v1
  kind: Job
  metadata:
    name: automation-broker-apb
    namespace: "${NAMESPACE}"
  spec:
    backoffLimit: 5
    activeDeadlineSeconds: 300
    template:
      spec:
        restartPolicy: OnFailure
        serviceAccount: automation-broker-apb
        containers:
        - image: docker.io/automationbroker/automation-broker-apb:${TAG}
          name: automation-broker-apb
          args: [ 'provision', '--extra-vars', '{ "broker_name": "${NAMESPACE}" }' ]


parameters:
- description: Namespace of the project that is being deploy
  displayname: Namespace
  name: NAMESPACE
  value: "openshift-automation-service-broker"

- description: Image Tag to deploy
  displayname: Image Tag
  name: TAG
  value: "latest"
