apiVersion: v1
kind: Template
metadata:
  name: openshift-logging-apb
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    namespace: ${NAMESPACE}
    name: openshift-logging-apb-admin-config
  type: Opaque
  data:
    admin.kubeconfig: "${ADMIN_KUBECONFIG}"

- apiVersion: v1
  kind: Secret
  metadata:
    namespace: ${NAMESPACE}
    name: openshift-logging-apb-certs
  type: Opaque

- apiVersion: batch/v1
  kind: Job
  metadata:
    name: openshift-logging-apb
    namespace: "${NAMESPACE}"
  spec:
    backoffLimit: 5
    activeDeadlineSeconds: 1800
    template:
      spec:
        restartPolicy: OnFailure
        containers:
        - image: docker.io/ansibleplaybookbundle/openshift-logging-apb:latest
          name: openshift-logging-apb
          args: [ "provision", "-e", "public_hostname=${PUBLIC_HOSTNAME}" ]
          volumeMounts:
          - mountPath: /tmp/logging-config
            name: admin-kubeconfig
          - mountPath: /tmp/logging-certs
            name: certs
        volumes:
        - name: admin-kubeconfig
          secret:
            defaultMode: 444
            secretName: openshift-logging-apb-admin-config
        - name: certs
          secret:
            defaultMode: 444
            secretName: openshift-logging-apb-certs

parameters:
- description: Namespace of the project that is being deploy
  displayname: broker client cert key
  name: NAMESPACE
  value: "openshift-logging"

- description: Cluster public hostname
  displayname: public hostname
  name: PUBLIC_HOSTNAME

- description: admin.kubeconfig file
  displayname: admin.kubeconfig
  name: ADMIN_KUBECONFIG
