language: go

go:
  - 1.7

install:
  - export PATH=$GOPATH/bin:./_output/tools/etcd/bin:$PATH
  - make install-travis

script:
  - OS_GOFLAGS="-p 1" travis_wait make build
  - PROTO_OPTIONAL=1 make verify
  - make verify-commits

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: false
