language: go

go:
  - 1.4
  - 1.5.1

install:
  - export PATH=$GOPATH/bin:./_tools/etcd/bin:$PATH
  - make install-travis

script:
  - make verify

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: false
