language: go

go:
  - 1.3
  - 1.4

env:
 - TEST_ASSETS=true
 - TEST_ASSETS=false

matrix:
  exclude:
    - go: 1.4
      env: TEST_ASSETS=true

install:
  - ./hack/verify-gofmt.sh
  - ./hack/install-etcd.sh
  - ./hack/install-std-race.sh
  - ./hack/install-tools.sh
  - ./hack/build-go.sh
  - ./hack/install-assets.sh

script:
  - KUBE_RACE="-race" KUBE_COVER="-cover -covermode=atomic" ./hack/test-go.sh "" -p=4
  - ./hack/test-cmd.sh
  - PATH=$HOME/gopath/bin:./_output/etcd/bin:$PATH ./hack/test-integration.sh -v
  - ./hack/test-assets.sh

notifications:
  irc: "chat.freenode.net#openshift-dev"

