language: go

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"

install:
  - export PATH=$GOPATH/bin:./_output/tools/etcd/bin:$PATH
  - make install-travis

script:
  - make verify-commits

notifications:
  irc: "chat.freenode.net#openshift-dev"

sudo: false
