language: go
sudo: false

go:
  - 1.7
  - 1.8
  - 1.9
  - 1.10.x
  - 1.11.x
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - export PATH=$GOPATH/bin:./_output/tools/etcd/bin:$PATH
  - make install-travis

script:
  - make verify-commits

notifications:
  irc: "chat.freenode.net#openshift-dev"
