apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    name: mysql
spec: 
  containers: 
    - image: mysql
      name: mysql
      volumeMounts:
        - name: mysql-ceph
          mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: foopass
      securityContext:
        capabilities: {}
        privileged: true  #privileged required for the rbd mount
  volumes:
    - name: mysql-ceph
      rbd: 
        monitors: #ip addr of the ceph monitor
          - 192.168.122.133:6789
        pool: rbd
        image: foo
        user: admin
        secretRef: 
          name: ceph-secret
        fsType: ext4
        readOnly: false
