apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: node-exporter
  annotations:
    "openshift.io/display-name": "Node Exporter"
    description: |
      Prometheus Node Exporter - expose node-level metrics for consumption by Prometheus.
    iconClass: icon-cogs
    tags: "monitoring,prometheus,time-series,node-exporter"
parameters:
- description: The namespace to instantiate node-exporter under. Defaults to 'kube-system'.
  name: NAMESPACE
  value: kube-system
- description: The location of the proxy image
  name: IMAGE_PROXY
  value: registry.svc.ci.openshift.org/ci/oauth-proxy:latest
- description: The location of the node-exporter image
  name: IMAGE_NODE_EXPORTER
  value: quay.io/prometheus/node-exporter:latest
- description: The session secret for the proxy
  name: SESSION_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{43}"
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: node-exporter
    namespace: "${NAMESPACE}"
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"node-exporter"}}'
# Allow the node-exporter to access data and mounts from the host,
# so that it can expose metrics about them.
- apiVersion: v1
  kind: SecurityContextConstraints
  metadata:
    name: node-exporter
  allowHostDirVolumePlugin: true
  allowHostNetwork: true
  allowHostPID: true
  allowHostPorts: true
  runAsUser:
    type: RunAsAny
  seLinuxContext:
    type: RunAsAny
  users:
  - system:serviceaccount:${NAMESPACE}:node-exporter
  volumes:
  - hostPath
  - secret
# Create a fully end-to-end TLS connection to the proxy
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: node-exporter
    namespace: "${NAMESPACE}"
  spec:
    to:
      name: node-exporter
    tls:
      termination: Reencrypt
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/scheme: https
      service.alpha.openshift.io/serving-cert-secret-name: node-exporter-tls
    labels:
      name: node-exporter
    name: node-exporter
    namespace: "${NAMESPACE}"
  spec:
    ports:
    - name: node-exporter
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      app: node-exporter
- apiVersion: v1
  kind: Secret
  metadata:
    name: node-exporter-proxy
    namespace: "${NAMESPACE}"
  stringData:
    session_secret: "${SESSION_SECRET}="
# Deploy Node Exporter behind an oauth proxy
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
      app: node-exporter
    name: node-exporter
    namespace: "${NAMESPACE}"
  spec:
    selector:
      matchLabels:
        app: node-exporter
    template:
      metadata:
        labels:
          app: node-exporter
        name: node-exporter
      spec:
        serviceAccountName: node-exporter
        containers:
        - name: oauth-proxy
          image: ${IMAGE_PROXY}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8443
            name: web
          args:
          - -https-address=:8443
          - -email-domain=*
          - -client-id=system:serviceaccount:${NAMESPACE}:node-exporter
          - -upstream=http://localhost:9100
          - -provider=openshift
          - -redirect-url=https:///oauth2/callback
          - '-openshift-sar={"namespace": "${NAMESPACE}", "verb": "list", "resource": "services"}'
          - -tls-cert=/etc/tls/private/tls.crt
          - -tls-key=/etc/tls/private/tls.key
          - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
          - -cookie-secret-file=/etc/proxy/secrets/session_secret
          - -skip-auth-regex=^/metrics
          volumeMounts:
          - mountPath: /etc/tls/private
            name: node-exporter-tls
          - mountPath: /etc/proxy/secrets
            name: secrets

        - name: node-exporter
          args:
          - -web.listen-address=localhost:9100
          image: ${IMAGE_NODE_EXPORTER}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: dev
            mountPath: /host/dev
          - name: proc
            mountPath: /host/proc
          - name: sys
            mountPath: /host/sys
          - name: rootfs
            mountPath: /rootfs

        restartPolicy: Always

        hostPID: true
        # TODO: When enabling this (to get better network metrics), the oauth proxy
        # would have to listen on a different port because 8443 is already in use on
        # the host. But what port can we safely assume to be unused? Figure out
        # what's best here.
        #
        # hostNetwork: true
        
        volumes:
        - name: secrets
          secret:
            secretName: node-exporter-proxy
        - name: node-exporter-tls
          secret:
            secretName: node-exporter-tls
        - name: proc
          hostPath:
            path: /proc
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: rootfs
          hostPath:
            path: /
