kind: Template
apiVersion: template.openshift.io/v1
parameters:
- name: NAMESPACE
  required: true
objects:
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: registry-registry-role-${NAMESPACE}
  roleRef:
    apiGroup: ""
    kind: ClusterRole
    name: system:registry
  subjects:
  - kind: ServiceAccount
    name: registry
    namespace: ${NAMESPACE}
