kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: application-liveness
roleRef:
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: application-liveness
