apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: service-catalog-rbac
parameters:
- name: NAMESPACE
  value: kube-service-catalog
- name: KUBE_SYSTEM_NAMESPACE
  value: kube-system
objects:
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: servicecatalog-serviceclass-viewer
  rules:
  - apiGroups:
    - servicecatalog.k8s.io
    resources:
    - clusterserviceclasses
    - clusterserviceplans
    verbs:
    - list
    - watch
    - get

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: servicecatalog-serviceclass-viewer-binding
  roleRef:
    name: servicecatalog-serviceclass-viewer
  groupNames:
  - system:authenticated

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: service-catalog-sar-creator-binding
  roleRef:
    name: sar-creator
  subjects:
  - kind: ServiceAccount
    name: service-catalog-apiserver
    namespace: ${NAMESPACE}

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: namespace-viewer
  rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - list
    - watch
    - get

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: service-catalog-namespace-viewer-binding
  roleRef:
    name: namespace-viewer
  subjects:
  - kind: ServiceAccount
    name: service-catalog-apiserver
    namespace: ${NAMESPACE}

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: service-catalog-controller-namespace-viewer-binding
  roleRef:
    name: namespace-viewer
  subjects:
  - kind: ServiceAccount
    name: service-catalog-controller
    namespace: ${NAMESPACE}

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: sar-creator
  rules:
  - apiGroups:
    - ""
    resources:
    - subjectaccessreviews.authorization.k8s.io
    verbs:
    - create

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: service-catalog-controller
  rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - update
    - patch
    - delete
    - get
    - list
    - watch
  - apiGroups:
    - servicecatalog.k8s.io
    resources:
    - clusterservicebrokers/status
    - clusterserviceclasses/status
    - clusterserviceplans/status
    - serviceinstances/status
    - servicebindings/status
    - servicebindings/finalizers
    - serviceinstances/reference
    verbs:
    - update
  - apiGroups:
    - servicecatalog.k8s.io
    resources:
    - clusterservicebrokers
    - serviceinstances
    - servicebindings
    verbs:
    - list
    - get
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - patch
    - create
  - apiGroups:
    - servicecatalog.k8s.io
    resources:
    - clusterserviceclasses
    - clusterserviceplans
    verbs:
    - create
    - delete
    - update
    - patch
    - get
    - list
    - watch
  - apiGroups:
    - settings.k8s.io
    resources:
    - podpresets
    verbs:
    - create
    - update
    - delete
    - get
    - list
    - watch

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: service-catalog-controller-binding
  roleRef:
    name: service-catalog-controller
  subjects:
  - kind: ServiceAccount
    name: service-catalog-controller
    namespace: ${NAMESPACE}
  
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: Role
  metadata:
    name: endpoint-accessor
  rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - list
    - watch
    - get
    - create
    - update

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    name: endpointer-accessor-binding
  roleRef:
    name: endpoint-accessor
    namespace: ${NAMESPACE}
  subjects:
  - kind: ServiceAccount
    namespace: ${NAMESPACE}
    name: service-catalog-controller

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    name: extension-apiserver-authentication-reader-binding
    namespace: ${KUBE_SYSTEM_NAMESPACE}
  roleRef:
    name: extension-apiserver-authentication-reader
    namespace: ${KUBE_SYSTEM_NAMESPACE}
  subjects:
  - kind: ServiceAccount
    name: service-catalog-apiserver
    namespace: ${NAMESPACE}

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: system:auth-delegator-binding
  roleRef:
    name: system:auth-delegator
  subjects:
  - kind: ServiceAccount
    name: service-catalog-apiserver
    namespace: ${NAMESPACE}

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  meta:
    name: system:openshift:service-catalog:aggregate-to-admin
    labels: 
      rbac.authorization.k8s.io/aggregate-to-admin: true
  rules:
  - apiGroups:
    - "servicecatalog.k8s.io"
    resources:
    - "serviceinstances"
    - "servicebindings"
    verbs:
    - create
    - update
    - delete
    - get
    - list
    - watch
    - patch
  - apiGroups:
    - settings.k8s.io
    resources:
    - podpresets
    verbs:
    - create
    - update
    - delete
    - get
    - list
    - watch

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  meta:
    name: system:openshift:service-catalog:aggregate-to-edit
    labels:
      rbac.authorization.k8s.io/aggregate-to-edit: true
  rules:
  - apiGroups:
    - servicecatalog.k8s.io
    resources:
    - serviceinstances
    - servicebindings
    verbs:
    - create
    - update
    - delete
    - get
    - list
    - watch
    - patch
  - apiGroups:
    - settings.k8s.io
    resources:
    - podpresets
    verbs:
    - create
    - update
    - delete
    - get
    - list
    - watch

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  meta:
    name: system:openshift:service-catalog:aggregate-to-view
    labels:
      rbac.authorization.k8s.io/aggregate-to-view: true
  rules:
  - apiGroups:
    - servicecatalog.k8s.io
    resources:
    - serviceinstances
    - servicebindings
    verbs:
    - get
    - list
    - watch

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  meta:
    name: system:openshift:clusterservicebroker-client
  rules:
  - apiGroups:
    - servicecatalog.k8s.io
    resources:
    - clusterservicebrokers
    verbs:
    - create
    - update
    - delete
    - get
    - list
    - watch
    - patch
