apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: IMAGE
  value: openshift/origin-control-plane:latest
- name: OPENSHIFT_PULL_POLICY
  value: Always
- name: NAMESPACE
  value: openshift-core-operators
- name: LOGLEVEL
  value: "0"

objects:

# When we have an orchestrating operator, it will do this
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: system:openshift:operator:service-cert-signer
  roleRef:
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    namespace: ${NAMESPACE}
    name: openshift-service-cert-signer-operator

# Everything below this point is temporary until we fix up the operators to apply rbac resources
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: system:openshift:controller:apiservice-cabundle-injector
  rules:
  - apiGroups:
    - apiregistration.k8s.io
    resources:
    - apiservices
    verbs:
    - get
    - list
    - watch
    - update
    - patch

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: system:openshift:controller:apiservice-cabundle-injector
  roleRef:
    kind: ClusterRole
    name: system:openshift:controller:apiservice-cabundle-injector
  subjects:
  - kind: ServiceAccount
    namespace: openshift-service-cert-signer
    name: apiservice-cabundle-injector-sa

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: system:openshift:controller:service-serving-cert-signer
  rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - deletecollection
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - get
    - list
    - watch
    - update
    - patch

- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: system:openshift:controller:service-serving-cert-signer
  roleRef:
    kind: ClusterRole
    name: system:openshift:controller:service-serving-cert-signer
  subjects:
  - kind: ServiceAccount
    namespace: openshift-service-cert-signer
    name: service-serving-cert-signer-sa
