apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: IMAGE
  value: openshift/origin-control-plane:latest
- name: OPENSHIFT_PULL_POLICY
  value: Always
- name: NAMESPACE
  value: openshift-core-operators
- name: LOGLEVEL
  value: "0"

objects:

# When we have an orchestrating operator, it will do this
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: system:openshift:operator:service-cert-signer
  roleRef:
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    namespace: ${NAMESPACE}
    name: openshift-service-cert-signer-operator
