kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: e2e-disruption-monitor
rules:
  - verbs:
      - list
    apiGroups:
      - ''
      - oauth.openshift.io
    resources:
      - oauthclients
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - list
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
