apiVersion: config.openshift.io/v1
kind: TestReporting
metadata:
  creationTimestamp: null
  name: cluster
spec:
  testsForFeatureGates:
  - featureGate: Example
    tests:
    - testName: '[sig-arch][OCPFeatureGate:Example] should only run FeatureGated test
        when enabled'
  - featureGate: HardwareSpeed
    tests:
    - testName: '[sig-etcd][OCPFeatureGate:HardwareSpeed][Serial] etcd is able to
        set the hardware speed to "" [Timeout:30m][apigroup:machine.openshift.io]'
    - testName: '[sig-etcd][OCPFeatureGate:HardwareSpeed][Serial] etcd is able to
        set the hardware speed to Slower [Timeout:30m][apigroup:machine.openshift.io]'
    - testName: '[sig-etcd][OCPFeatureGate:HardwareSpeed][Serial] etcd is able to
        set the hardware speed to Standard [Timeout:30m][apigroup:machine.openshift.io]'
  - featureGate: NetworkDiagnosticsConfig
    tests:
    - testName: '[sig-network][OCPFeatureGate:NetworkDiagnosticsConfig][Serial] Should
        be enabled by default'
    - testName: '[sig-network][OCPFeatureGate:NetworkDiagnosticsConfig][Serial] Should
        function without any target pods'
    - testName: '[sig-network][OCPFeatureGate:NetworkDiagnosticsConfig][Serial] Should
        move the source diagnostics pods based on the new selector and tolerations'
    - testName: '[sig-network][OCPFeatureGate:NetworkDiagnosticsConfig][Serial] Should
        move the target diagnostics pods based on the new selector and tolerations'
    - testName: '[sig-network][OCPFeatureGate:NetworkDiagnosticsConfig][Serial] Should
        remove all network diagnostics pods when disabled'
    - testName: '[sig-network][OCPFeatureGate:NetworkDiagnosticsConfig][Serial] Should
        set the condition to false if there are no nodes able to host the source pods'
  - featureGate: VSphereDriverConfiguration
    tests:
    - testName: '[sig-storage][FeatureGate:VSphereDriverConfiguration][Serial][apigroup:operator.openshift.io]
        vSphere CSI Driver Configuration snapshot options in clusterCSIDriver should
        allow all limits to be set at once'
    - testName: '[sig-storage][FeatureGate:VSphereDriverConfiguration][Serial][apigroup:operator.openshift.io]
        vSphere CSI Driver Configuration snapshot options in clusterCSIDriver should
        allow setting VSAN limit'
    - testName: '[sig-storage][FeatureGate:VSphereDriverConfiguration][Serial][apigroup:operator.openshift.io]
        vSphere CSI Driver Configuration snapshot options in clusterCSIDriver should
        allow setting VVOL limit'
    - testName: '[sig-storage][FeatureGate:VSphereDriverConfiguration][Serial][apigroup:operator.openshift.io]
        vSphere CSI Driver Configuration snapshot options in clusterCSIDriver should
        allow setting global snapshot limit'
    - testName: '[sig-storage][FeatureGate:VSphereDriverConfiguration][Serial][apigroup:operator.openshift.io]
        vSphere CSI Driver Configuration snapshot options in clusterCSIDriver should
        use default when unset'
  - featureGate: ValidatingAdmissionPolicy
    tests:
    - testName: '[sig-api-machinery] ValidatingAdmissionPolicy [Privileged:ClusterAdmin]
        [FeatureGate:ValidatingAdmissionPolicy] [Beta] should allow expressions to
        refer variables.'
    - testName: '[sig-api-machinery] ValidatingAdmissionPolicy [Privileged:ClusterAdmin]
        [FeatureGate:ValidatingAdmissionPolicy] [Beta] should type check a CRD'
    - testName: '[sig-api-machinery] ValidatingAdmissionPolicy [Privileged:ClusterAdmin]
        [FeatureGate:ValidatingAdmissionPolicy] [Beta] should type check validation
        expressions'
    - testName: '[sig-api-machinery] ValidatingAdmissionPolicy [Privileged:ClusterAdmin]
        [FeatureGate:ValidatingAdmissionPolicy] [Beta] should validate against a Deployment'
status: {}
