apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-network-disruption-poller
spec:
  # to be overridden by the number of nodes
  replicas: 1
  selector:
    matchLabels:
      network.openshift.io/disruption-target: pod-network
      network.openshift.io/disruption-actor: poller
  template:
    metadata:
      labels:
        network.openshift.io/disruption-target: pod-network
        network.openshift.io/disruption-actor: poller
    spec:
      containers:
        - command:
            - /openshift-tests disruption watch-endpoint-slice
            - --output-file=disruption.jsonl
              --disruption-backend-prefix=pod-to-pod-
              --disruption-target-service-name=pod-network-service
          image: registry.k8s.io/e2e-test-images/agnhost:2.43
          imagePullPolicy: IfNotPresent
          name: disruption-poller
          terminationMessagePolicy: FallbackToLogsOnError
      restartPolicy: Always
      terminationGracePeriodSeconds: 70
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  network.openshift.io/disruption-target: pod-network
                  network.openshift.io/disruption-actor: poller
