apiVersion: v1
kind: Service
metadata:
  name: pod-network-service
spec:
  selector:
    network.openshift.io/disruption-target: pod-network
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080