apiVersion: v1
kind: Service
metadata:
  name: host-network-service
spec:
  selector:
    network.openshift.io/disruption-target: host-network
    network.openshift.io/disruption-actor: target
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080