apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: openshift-apiserver
parameters:
- name: IMAGE
  value: openshift/origin-control-plane:latest
- name: OPENSHIFT_PULL_POLICY
  value: Always
- name: NAMESPACE
  value: openshift-apiserver
- name: LOGLEVEL
  value: "0"
- name: OPENSHIFT_APISERVER_CONFIG_HOST_PATH
- name: NODE_SELECTOR
  value: "{}"
objects:

- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    namespace: ${NAMESPACE}
    name: openshift-apiserver
    labels:
      openshift.io/control-plane: "true"
      openshift.io/component: api
  spec:
    selector:
      matchLabels:
        openshift.io/control-plane: "true"
        openshift.io/component: api
    template:
      metadata:
        name: openshift-apiserver
        labels:
          openshift.io/control-plane: "true"
          openshift.io/component: api
      spec:
        serviceAccountName: openshift-apiserver
        restartPolicy: Always
        hostNetwork: true
        containers:
        - name: apiserver
          image: ${IMAGE}
          imagePullPolicy: ${OPENSHIFT_PULL_POLICY}
          env:
          - name: ADDITIONAL_ALLOWED_REGISTRIES
            value: registry.centos.org
          command: ["hypershift", "openshift-apiserver"]
          args:
          - "--config=/etc/origin/master/master-config.yaml"
          - "-v=${LOGLEVEL}"
          ports:
          - containerPort: 8445
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
          - mountPath: /var/serving-cert
            name: serving-cert
          - mountPath: /etc/origin/master/
            name: master-config
          - mountPath: /etc/origin/cloudprovider/
            name: master-cloud-provider
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8445
              scheme: HTTPS
        # sensitive files still sit on disk for now
        volumes:
        - name: master-config
          hostPath:
            path: ${OPENSHIFT_APISERVER_CONFIG_HOST_PATH}
        - name: master-cloud-provider
          hostPath:
            path: /etc/origin/cloudprovider
        - name: serving-cert
          secret:
            secretName: serving-cert


# to be able to assign powers to the process
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: ${NAMESPACE}
    name: openshift-apiserver

- apiVersion: v1
  kind: Service
  metadata:
    namespace: ${NAMESPACE}
    name: api
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: serving-cert
  spec:
    selector:
      openshift.io/component: api
    ports:
    - name: https
      port: 443
      targetPort: 8445

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.apps.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: apps.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.authorization.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: authorization.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.build.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: build.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.image.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: image.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.network.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: network.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.oauth.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: oauth.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.project.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: project.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.quota.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: quota.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.route.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: route.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.security.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: security.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.template.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: template.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15

- apiVersion: apiregistration.k8s.io/v1beta1
  kind: APIService
  metadata:
    name: v1.user.openshift.io
    annotations:
      service.alpha.openshift.io/inject-cabundle: "true"
  spec:
    group: user.openshift.io
    version: v1
    service:
      namespace: openshift-apiserver
      name: api
    groupPriorityMinimum: 9900
    versionPriority: 15
