apiVersion: openshiftcontrolplane.config.openshift.io/v1
kind: OpenShiftAPIServerConfig
kubeClientConfig:
  kubeConfig: openshift-apiserver.kubeconfig
apiServerArguments:
  storage-backend:
  - etcd3
  storage-media-type:
  - application/vnd.kubernetes.protobuf
corsAllowedOrigins:
- //127\.0\.0\.1(:|$)
- //localhost(:|$)
servingInfo:
  bindAddress: 0.0.0.0:8444
  bindNetwork: tcp4
  certFile: serving-openshift-apiserver.crt
  clientCA: client-ca.crt
  keyFile: serving-openshift-apiserver.key
  maxRequestsInFlight: 1200
  namedCertificates: null
  requestTimeoutSeconds: 3600
storageConfig:
  ca: etcd-serving-ca.crt
  certFile: client-etcd-client.crt
  keyFile: client-etcd-client.key
  urls:
  - https://127.0.0.1:2379

