apiVersion: openshiftcontrolplane.config.openshift.io/v1
kind: OpenShiftControllerManagerConfig
kubeClientConfig:
  kubeConfig: openshift-controller-manager.kubeconfig
corsAllowedOrigins:
- //127\.0\.0\.1(:|$)
- //localhost(:|$)
servingInfo:
  bindAddress: 0.0.0.0:8445
  bindNetwork: tcp4
  certFile: serving-openshift-controller-manager.crt
  clientCA: client-ca.crt
  keyFile: serving-openshift-controller-manager.key
  maxRequestsInFlight: 1200
  namedCertificates: null
  requestTimeoutSeconds: 3600
