apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cleanup
  namespace: e2e-disruption-monitor
spec:
  selector:
    matchLabels:
      app: cleanup
  template:
    metadata:
      labels:
        app: cleanup
    spec:
      containers:
      - name: cleanup
        command:
        - bash
        - -c
        - |
          rm -rf /var/log/disruption-data && sleep infinity
        image: "image-registry.openshift-image-registry.svc:5000/openshift/tests:latest"
        volumeMounts:
        - mountPath: /var/log/disruption-data
          name: artifacts
      hostNetwork: true
      serviceAccountName: disruption-monitor-sa
      securityContext:
        privileged: true
        runAsUser: 0
      terminationGracePeriodSeconds: 90
      volumes:
      - hostPath:
          path: /var/log/disruption-data
          type: DirectoryOrCreate
        name: artifacts
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
