apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: internal-lb-monitor
  namespace: e2e-disruption-monitor
spec:
  selector:
    matchLabels:
      app: internal-lb-monitor
      network.openshift.io/disruption-actor: poller
  template:
    metadata:
      labels:
        app: internal-lb-monitor
        network.openshift.io/disruption-actor: poller
    spec:
      containers:
      - name: internal-lb
        command:
        - openshift-tests
        - run-disruption
        - --output-file=/var/log/disruption-data/monitor-events/internal-lb.txt
        - --lb-type $(LOAD_BALANCER)
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: api-int.foo.bar
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
        - name: LOAD_BALANCER
          value: "internal-lb"
        - name: EXTRA_MESSAGE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: "image-registry.openshift-image-registry.svc:5000/openshift/tests:latest"
        volumeMounts:
        - mountPath: /var/log/disruption-data
          name: artifacts
      hostNetwork: true
      serviceAccountName: disruption-monitor-sa
      securityContext:
        privileged: true
        runAsUser: 0
      terminationGracePeriodSeconds: 90
      volumes:
      - hostPath:
          path: /var/log/disruption-data
          type: DirectoryOrCreate
        name: artifacts
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
