apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    name: mysql
spec: 
  containers: 
    - image: mysql
      name: mysql
      volumeMounts:
        - name: varlibmysql
          mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: foopass
  volumes:
    - name: varlibmysql
      hostPath: 
        path: /opt/mysql
